# -*- coding: utf-8 -*-
"""CPS_XAI (4).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fw5tZkEoy2kOXHZkYfWsqcUzjgkeQki8
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import itertools
import random
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import SGDClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

df = pd.read_csv("KDDTrain.csv")
test_df = pd.read_csv("KDDTest.csv")

columns = (['duration'
,'protocol_type'
,'service'
,'flag'
,'src_bytes'
,'dst_bytes'
,'land'
,'wrong_fragment'
,'urgent'
,'hot'
,'num_failed_logins'
,'logged_in'
,'num_compromised'
,'root_shell'
,'su_attempted'
,'num_root'
,'num_file_creations'
,'num_shells'
,'num_access_files'
,'num_outbound_cmds'
,'is_host_login'
,'is_guest_login'
,'count'
,'srv_count'
,'serror_rate'
,'srv_serror_rate'
,'rerror_rate'
,'srv_rerror_rate'
,'same_srv_rate'
,'diff_srv_rate'
,'srv_diff_host_rate'
,'dst_host_count'
,'dst_host_srv_count'
,'dst_host_same_srv_rate'
,'dst_host_diff_srv_rate'
,'dst_host_same_src_port_rate'
,'dst_host_srv_diff_host_rate'
,'dst_host_serror_rate'
,'dst_host_srv_serror_rate'
,'dst_host_rerror_rate'
,'dst_host_srv_rerror_rate'
,'attack'
,'level'])

df.columns = columns
test_df.columns = columns

is_attack = df.attack.map(lambda a: 0 if a == 'normal' else 1)
test_attack = test_df.attack.map(lambda a: 0 if a == 'normal' else 1)

df['attack_flag'] = is_attack
test_df['attack_flag'] = test_attack

dos_attacks = ['apache2','back','land','neptune','mailbomb','pod','processtable','smurf','teardrop','udpstorm','worm']
probe_attacks = ['ipsweep','mscan','nmap','portsweep','saint','satan']
privilege_attacks = ['buffer_overflow','loadmdoule','perl','ps','rootkit','sqlattack','xterm']
access_attacks = ['ftp_write','guess_passwd','http_tunnel','imap','multihop','named','phf','sendmail','snmpgetattack','snmpguess','spy','warezclient','warezmaster','xclock','xsnoop']


attack_labels = ['Normal','DoS','Probe','Privilege','Access']

def map_attack(attack):
    if attack in dos_attacks:
        attack_type = 1
    elif attack in probe_attacks:
        attack_type = 2
    elif attack in privilege_attacks:
        attack_type = 3
    elif attack in access_attacks:
        attack_type = 4
    else:
        attack_type = 0
    return attack_type

attack_map = df.attack.apply(map_attack)
df['attack_map'] = attack_map
test_attack_map = test_df.attack.apply(map_attack)
test_df['attack_map'] = test_attack_map
df.head()

"""Understanding relationship and causality between attack and protocol"""

attack_vs_protocol = pd.crosstab(df.attack, df.protocol_type)

def bake_pies(data_list,labels):
    list_length = len(data_list)

    color_list = sns.color_palette()
    color_cycle = itertools.cycle(color_list)
    cdict = {}

    fig, axs = plt.subplots(1, list_length,figsize=(18,10), tight_layout=False)
    plt.subplots_adjust(wspace=1/list_length)

    for count, data_set in enumerate(data_list):
        for num, value in enumerate(np.unique(data_set.index)):
            if value not in cdict:
                cdict[value] = next(color_cycle)
        wedges,texts = axs[count].pie(data_set,
                           colors=[cdict[v] for v in data_set.index])
        axs[count].legend(wedges, data_set.index,
                           title="Flags",
                           loc="center left",
                           bbox_to_anchor=(1, 0, 0.5, 1))
        axs[count].set_title(labels[count])
    return axs

icmp_attacks = attack_vs_protocol.icmp
tcp_attacks = attack_vs_protocol.tcp
udp_attacks = attack_vs_protocol.udp
bake_pies([icmp_attacks, tcp_attacks, udp_attacks],['icmp','tcp','udp'])
plt.show()

normal_flags = df.loc[df.attack_flag == 0].flag.value_counts()
attack_flags = df.loc[df.attack_flag == 1].flag.value_counts()
flag_axs = bake_pies([normal_flags, attack_flags], ['normal','attack'])
plt.show()

features_to_encode = ['protocol_type', 'service', 'flag']
encoded = pd.get_dummies(df[features_to_encode])
test_encoded_base = pd.get_dummies(test_df[features_to_encode])
test_index = np.arange(len(test_df.index))
column_diffs = list(set(encoded.columns.values)-set(test_encoded_base.columns.values))
diff_df = pd.DataFrame(0, index=test_index, columns=column_diffs)
column_order = encoded.columns.to_list()
test_encoded_temp = test_encoded_base.join(diff_df)
test_final = test_encoded_temp[column_order].fillna(0)
numeric_features = ['duration', 'src_bytes', 'dst_bytes']
to_fit = encoded.join(df[numeric_features])
test_set = test_final.join(test_df[numeric_features])

binary_y = df['attack_flag']
multi_y = df['attack_map']
test_binary_y = test_df['attack_flag']
test_multi_y = test_df['attack_map']
binary_train_X, binary_val_X, binary_train_y, binary_val_y = train_test_split(to_fit, binary_y, test_size=0.6)
multi_train_X, multi_val_X, multi_train_y, multi_val_y = train_test_split(to_fit, multi_y, test_size = 0.6)

models = [
    LogisticRegression(max_iter=250),
    DecisionTreeClassifier(max_depth=10),
    RandomForestClassifier(),
    KNeighborsClassifier(),
    GaussianNB()
]

model_comps = []
for model in models:
    model_name = model.__class__.__name__
    accuracies = cross_val_score(model, binary_train_X, binary_train_y, scoring='accuracy')
    for count, accuracy in enumerate(accuracies):
        model_comps.append((model_name, count, accuracy))

recalls = np.array([0.87238, 0.97812, 0.90601, 0.67129, 0.46921])
recalls

result_df = pd.DataFrame(model_comps, columns=['model_name', 'count', 'accuracy'])
print("Box Plot of Accuracy Scores")
result_df.pivot(index='count',columns='model_name',values='accuracy').boxplot(rot=45)

result_df = result_df.groupby('model_name').mean()
result_df

models = np.array(['RandomForest', 'DTree', 'KNN', 'LogReg', 'GaussianNB'])
accuracies =result_df['accuracy'].values
accuracies= sorted(accuracies, reverse=True)
print("Models: ",models)
print("Accuracies: ",accuracies)
print("Recalls: ",recalls)

X_axis = np.arange(len(models))

plt.bar(X_axis - 0.2, accuracies, 0.4, label = 'Accuracy')
plt.bar(X_axis + 0.2, recalls, 0.4, label = 'Recall')

plt.xticks(X_axis, models)
plt.xlabel("Machine Learning Models")
plt.ylabel("Score")
plt.title("Performance Evaluation Metrics")
plt.legend()
plt.show()

#Decision Tree
clf = DecisionTreeClassifier() #max_depth=10
clf = clf.fit(binary_train_X, binary_train_y)
clf_predictions = clf.predict(binary_val_X)
train_acc = clf.score(binary_train_X, binary_train_y)
base_clf_score = accuracy_score(clf_predictions,binary_val_y)
print("Training accuracy is:", train_acc*100 )
print("Testing accuracy is:", base_clf_score*100)

#Decision Tree Performance Metrics
from sklearn.metrics import accuracy_score, f1_score, precision_score,recall_score
Tree_f1 = f1_score(binary_val_y, clf_predictions, average="macro")
Tree_precision = precision_score(binary_val_y, clf_predictions, average="macro")
Tree_recall = recall_score(binary_val_y, clf_predictions, average="macro")
Tree_accuracy = accuracy_score(binary_val_y, clf_predictions)
cm_dtree = confusion_matrix(binary_val_y, clf_predictions)
print('Confusion Matrix: ')
print(cm_dtree)
print("Accuracy Score: ", Tree_f1)
print("Precision Score: ", Tree_precision)
print("Recall Score: ", Tree_recall)
print("F1 Score: ", Tree_accuracy)

def add_predictions(data_set,predictions,y):
    prediction_series = pd.Series(predictions, index=y.index)

    predicted_vs_actual = data_set.assign(predicted=prediction_series)
    original_data = predicted_vs_actual.assign(actual=y).dropna()
    conf_matrix = confusion_matrix(original_data['actual'],
                                   original_data['predicted'])

    # capture rows with failed predictions
    base_errors = original_data[original_data['actual'] != original_data['predicted']]

    # drop columns with no value
    non_zeros = base_errors.loc[:,(base_errors != 0).any(axis=0)]

    # identify the type of error
    false_positives = non_zeros.loc[non_zeros.actual==0]
    false_negatives = non_zeros.loc[non_zeros.actual==1]

    # put everything into an object
    prediction_data = {'data': original_data,
                       'confusion_matrix': conf_matrix,
                       'errors': base_errors,
                       'non_zeros': non_zeros,
                       'false_positives': false_positives,
                       'false_negatives': false_negatives}
    return prediction_data

binary_prediction_data = add_predictions(df,
                                         clf_predictions,
                                         binary_val_y)

sns.heatmap(data=binary_prediction_data['confusion_matrix'],
            xticklabels = ['Predicted Normal','Predicted Attack'],
            yticklabels = ['Actual Normal','Actual Attack'],
            cmap="YlGnBu",
            fmt='d',
            annot=True)

binary_prediction_data['errors'].describe()

binary_prediction_data['false_negatives']

"""## Explainable AI with LIME"""

data = pd.read_csv("KDDTrain.csv")
data.columns = columns
data.drop(['level'], axis=1, inplace=True)
data

attacks = data['attack'].unique()
attacks

catCols = data.select_dtypes(include = "object").columns
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
for feat in catCols:
    data[feat] = le.fit_transform(data[feat].astype(str))
data.head()

from sklearn.model_selection import train_test_split
x = data.iloc[:,:-1]
y = data.iloc[:,-1]

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)
y_test

model = DecisionTreeClassifier(random_state=18)
model.fit(x_train, y_train)

# Install lime
# Note: In a script, use pip.main or subprocess instead of '!' syntax
import sys
import subprocess
try:
    import lime
except ImportError:
    subprocess.check_call([sys.executable, "-m", "pip", "install", "lime"])
    import lime

from lime import lime_tabular

explainer = lime_tabular.LimeTabularExplainer(
    training_data=np.array(x_train),
    feature_names=x_train.columns,
    class_names=attacks,
    mode='classification'
)

y_test.mode()

"""### LIME interpretation for different attacks in the test dataset

"""

import warnings
warnings.filterwarnings("ignore", category=UserWarning)
for i in range(1, 5):
    exp = explainer.explain_instance(data_row=x_train.iloc[i],
                                     predict_fn=model.predict_proba)

    exp.show_in_notebook(show_table=True)

for i in range(1, 5):  # Explaining multiple attack samples
    exp = explainer.explain_instance(data_row=x_test.iloc[i],
                                     predict_fn=model.predict_proba)

    print(f"Instance {i} Explanation:")
    print(exp.as_list())  # Get feature importance for this prediction
    exp.show_in_notebook(show_table=True)

"""## Explainable AI with SHAP"""

# Install shap if not already installed
try:
    import shap
except ImportError:
    subprocess.check_call([sys.executable, "-m", "pip", "install", "shap"])
    import shap

# Fit the SHAP explainer
explainer = shap.Explainer(model.predict, x_test)
# Calculate SHAP values
shap_values = explainer(x_test)

# Get expected value correctly
expected_value = shap_values.base_values.mean()  # Approximate expected value

# Ensure correct indexing for force plot
instance_index = 0  # Change this for different instances

# Visualizing the force plot
shap.initjs()
shap.force_plot(expected_value, shap_values[instance_index].values, x_test.iloc[instance_index])

# Bar Plot
shap.plots.bar(shap_values)

# Summary Plot (Beeswarm)
shap.plots.beeswarm(shap_values)

# Summary Plot (Violin)
shap.summary_plot(shap_values, plot_type='violin')

# Local Bar Plot
shap.plots.bar(shap_values[0])

# Waterfall Plot
shap.plots.waterfall(shap_values[0])

"""# Providing Explanation using SHAP"""

# Updated detection function
def detect_intrusion(new_data_row):
    # Step 1: Preprocess
    processed_row = scaler.transform(new_data_row)

    # Step 2: Predict
    prediction_index = model.predict(processed_row)[0]
    prediction_label = attacks[prediction_index]  # Get actual attack name
    probability = model.predict_proba(processed_row)[0]

    # Step 3: Map attack to category
    attack_type_code = map_attack(prediction_label)
    attack_type = attack_labels[attack_type_code]

    # Step 4: Explain
    shap_values = explainer(pd.DataFrame(processed_row, columns=new_data_row.columns))
    shap.plots.waterfall(shap_values[0])

    # Step 5: Get contributing reasons
    reasons = []
    feature_names = new_data_row.columns
    instance_vals = new_data_row.values[0]
    shap_contribs = shap_values.values[0]

    for feat, val, contrib in zip(feature_names, instance_vals, shap_contribs):
        if contrib > 0:
            reasons.append(f"{feat} = {val} -> contributed to classification (+{contrib:.3f})")

    return prediction_label, attack_type, probability, reasons

for idx in range(100, 104):  # Checking: 100 to 104 rows in x_test
    new_data_row = x_test.iloc[idx:idx+1]

    pred_label, pred_type, probs, reasons = detect_intrusion(new_data_row)

    print(f"\n🔍 Instance {idx}")
    print(f"Predicted Attack: {pred_label}")
    print(f"Attack Type: {pred_type}")
    print("Probabilities:", probs)
    print("Reasons for classification:")
    for reason in reasons:
        print("-", reason)

"""## Explainable AI with Hierarchical Counterfactual Explanations"""

class HierarchicalCounterfactualExplainer:
    """
    Implements Hierarchical Counterfactual Explanations for classification models
    that works with both categorical and numerical features.
    Specifically focused on explaining how to convert Attack instances to Normal.
    """
    
    def __init__(self, model, feature_names, categorical_indices=None, 
                 numerical_indices=None, class_names=None):
        """
        Initialize the explainer.
        
        Args:
            model: The trained model for which explanations are generated
            feature_names: List of all feature names
            categorical_indices: List of indices for categorical features
            numerical_indices: List of indices for numerical features
            class_names: List of class names
        """
        self.model = model
        self.feature_names = feature_names
        self.categorical_indices = categorical_indices or []
        self.numerical_indices = numerical_indices or []
        self.class_names = class_names or ["Normal", "Attack"]
        
        # Extract feature importance from the model (if available)
        if hasattr(model, 'feature_importances_'):
            self.feature_importances = model.feature_importances_
        else:
            # If model doesn't have feature importances, use uniform weights
            self.feature_importances = np.ones(len(feature_names)) / len(feature_names)
            
        # Create feature importance ranking
        self.feature_importance_ranking = np.argsort(self.feature_importances)[::-1]
        
    def fit(self, X_train, y_train=None):
        """
        Fit the explainer on training data.
        
        Args:
            X_train: Training data features
            y_train: Training data labels (optional)
        """
        # Store training data for counterfactual generation
        self.X_train = X_train.values if hasattr(X_train, 'values') else X_train
        
        # If y_train is provided, store it for more efficient candidate selection
        if y_train is not None:
            self.y_train = y_train.values if hasattr(y_train, 'values') else y_train
        else:
            self.y_train = None
        
        return self
    
    def _predict_prob(self, instance):
        """
        Get model prediction probabilities for an instance.
        
        Args:
            instance: The instance to predict
            
        Returns:
            Prediction probabilities
        """
        if isinstance(instance, np.ndarray) and instance.ndim == 1:
            instance = instance.reshape(1, -1)
        return self.model.predict_proba(instance)[0]
    
    def _predict_class(self, instance):
        """
        Get model prediction class for an instance.
        
        Args:
            instance: The instance to predict
            
        Returns:
            Predicted class
        """
        if isinstance(instance, np.ndarray) and instance.ndim == 1:
            instance = instance.reshape(1, -1)
        return self.model.predict(instance)[0]
    
    def _distance(self, x1, x2, weighted=True):
        """
        Calculate distance between two instances, handling categorical and numerical features.
        
        Args:
            x1: First instance
            x2: Second instance
            weighted: Whether to use feature importance weighting
            
        Returns:
            Distance value
        """
        if weighted:
            weights = self.feature_importances
        else:
            weights = np.ones(len(self.feature_names))
        
        # Initialize squared distance
        squared_dist = 0
        
        # Calculate distance for each feature
        for i in range(len(x1)):
            # Use different distance measures for categorical vs numerical
            if i in self.categorical_indices:
                # For categorical, use simple match/mismatch (0/1)
                diff = 0 if x1[i] == x2[i] else 1
            else:
                # For numerical, use squared difference
                diff = (x1[i] - x2[i]) ** 2
            
            # Add weighted contribution to distance
            squared_dist += weights[i] * diff
            
        return np.sqrt(squared_dist)
    
    def _generate_counterfactual_candidates(self, instance, target_class=0, num_candidates=100):
        """
        Generate candidate counterfactuals from training data.
        Default target_class=0 for "Normal" instances.
        
        Args:
            instance: The instance to explain
            target_class: The target class for counterfactuals
            num_candidates: Number of candidates to generate
            
        Returns:
            List of candidate counterfactuals
        """
        # Reshape instance if needed
        if isinstance(instance, np.ndarray) and instance.ndim == 1:
            instance = instance.reshape(1, -1)
        
        # Find instances of the target class
        target_indices = []
        
        # If we have stored y_train, use it for more efficient selection
        if self.y_train is not None:
            target_indices = np.where(self.y_train == target_class)[0]
        else:
            # Otherwise predict on each training instance
            for i in range(len(self.X_train)):
                if self._predict_class(self.X_train[i]) == target_class:
                    target_indices.append(i)
        
        # If no target class instances found, return empty list
        if len(target_indices) == 0:
            return []
        
        # Calculate distances to target class instances
        distances = []
        for idx in target_indices:
            dist = self._distance(instance[0], self.X_train[idx])
            distances.append((idx, dist))
        
        # Sort by distance and take the closest ones
        distances.sort(key=lambda x: x[1])
        closest_indices = [idx for idx, _ in distances[:min(num_candidates, len(distances))]]
        
        # Return the candidates
        return [self.X_train[idx].copy() for idx in closest_indices]
    
    def _evaluate_counterfactual(self, original, counterfactual, target_class):
        """
        Evaluate a counterfactual candidate.
        
        Args:
            original: Original instance
            counterfactual: Counterfactual instance
            target_class: Target class
            
        Returns:
            Dictionary with evaluation metrics
        """
        # Check if counterfactual achieves target class
        cf_class = self._predict_class(counterfactual)
        valid = (cf_class == target_class)
        
        # Calculate sparsity (number of changed features)
        changes = np.zeros(len(original), dtype=bool)
        for i in range(len(original)):
            if i in self.categorical_indices:
                # For categorical features, any difference counts as change
                changes[i] = original[i] != counterfactual[i]
            else:
                # For numerical features, use a threshold to determine change
                # to account for very small floating point differences
                changes[i] = abs(original[i] - counterfactual[i]) > 1e-6
                
        sparsity = np.sum(changes)
        
        # Calculate distance
        distance = self._distance(original, counterfactual)
        
        # Calculate feature importance weighted changes
        weighted_changes = 0
        for i in range(len(changes)):
            if changes[i]:
                weighted_changes += self.feature_importances[i]
        
        return {
            'valid': valid,
            'sparsity': sparsity,
            'distance': distance,
            'weighted_changes': weighted_changes,
            'counterfactual': counterfactual,
            'changed_indices': np.where(changes)[0]
        }
    
    def generate_hierarchical_counterfactuals(self, instance, target_class=0, 
                                             num_hierarchies=3, max_iterations=100):
        """
        Generate hierarchical counterfactual explanations.
        Default target_class=0 for "Normal" instances.
        
        Args:
            instance: The instance to explain
            target_class: The target class (default is 0 for "Normal")
            num_hierarchies: Number of hierarchy levels to generate
            max_iterations: Maximum number of iterations per hierarchy level
            
        Returns:
            List of counterfactuals at different hierarchy levels
        """
        # Ensure instance is a 1D array
        if hasattr(instance, 'values'):
            instance = instance.values
        
        if instance.ndim == 2 and instance.shape[0] == 1:
            instance = instance[0]
            
        # Determine original class
        original_class = self._predict_class(instance)
        
        # If instance is already of target class, no counterfactual needed
        if original_class == target_class:
            print(f"Instance is already of class {target_class} ({self.class_names[target_class]})")
            return [instance]
        
        # Generate initial counterfactual candidates
        candidates = self._generate_counterfactual_candidates(instance, target_class)
        
        if not candidates:
            print(f"No candidates found for target class {target_class} ({self.class_names[target_class]})")
            return []
        
        # Create hierarchical counterfactuals
        hierarchical_counterfactuals = []
        current_instance = instance.copy()
        
        # Divide features into hierarchical levels based on importance
        feature_indices = self.feature_importance_ranking
        features_per_level = max(1, len(feature_indices) // num_hierarchies)
        
        for h in range(num_hierarchies):
            start_idx = h * features_per_level
            end_idx = min((h + 1) * features_per_level, len(feature_indices))
            level_features = feature_indices[start_idx:end_idx]
            
            # Search for the best counterfactual at this level
            best_counterfactual = None
            best_score = float('inf')
            best_evaluation = None
            
            for _ in range(max_iterations):
                # Select a random candidate
                if not candidates:
                    break
                    
                candidate_idx = random.randint(0, len(candidates) - 1)
                candidate = candidates[candidate_idx]
                
                # Create a new counterfactual by modifying only the level's features
                counterfactual = current_instance.copy()
                for feat_idx in level_features:
                    counterfactual[feat_idx] = candidate[feat_idx]
                
                # Evaluate the counterfactual
                evaluation = self._evaluate_counterfactual(current_instance, counterfactual, target_class)
                
                # Update best counterfactual if valid and better
                if evaluation['valid']:
                    # Score based on distance and sparsity
                    score = evaluation['distance'] + evaluation['sparsity'] * 0.1
                    if score < best_score:
                        best_counterfactual = counterfactual
                        best_score = score
                        best_evaluation = evaluation
            
            # If found a valid counterfactual at this level, add it to the hierarchy
            if best_counterfactual is not None:
                hierarchical_counterfactuals.append({
                    'counterfactual': best_counterfactual,
                    'evaluation': best_evaluation
                })
                current_instance = best_counterfactual
                
                # If already reached target class, we're done
                if self._predict_class(current_instance) == target_class:
                    break
            else:
                # If no valid counterfactual found at this level, try more features
                continue
                
        return hierarchical_counterfactuals
    
    def explain_instance(self, instance, target_class=0, num_hierarchies=3):
        """
        Generate and explain hierarchical counterfactuals for an instance.
        Default target_class=0 for "Normal" instances.
        
        Args:
            instance: The instance to explain
            target_class: The target class for counterfactuals (default 0 for "Normal")
            num_hierarchies: Number of hierarchy levels
            
        Returns:
            Dictionary containing explanations
        """
        # Generate hierarchical counterfactuals
        hierarchical_cfs = self.generate_hierarchical_counterfactuals(
            instance, target_class, num_hierarchies)
        
        if not hierarchical_cfs:
            return {"success": False, "message": "No counterfactuals found"}
        
        # Prepare explanation
        original_class = self._predict_class(instance)
        explanations = []
        
        print("\nHierarchical Counterfactual Explanation:")
        print(f"Original prediction: Class {original_class} ({self.class_names[original_class]})")
        print(f"Target class: Class {target_class} ({self.class_names[target_class]})")
        
        current = instance
        
        for i, cf_dict in enumerate(hierarchical_cfs):
            cf = cf_dict['counterfactual']
            evaluation = cf_dict['evaluation']
            changed_indices = evaluation['changed_indices']
            
            # Find changed features
            changed_features = []
            for j in changed_indices:
                feature_name = self.feature_names[j]
                changed_features.append({
                    "feature": feature_name,
                    "original_value": current[j],
                    "counterfactual_value": cf[j],
                    "importance": self.feature_importances[j]
                })
            
            # Sort changed features by importance
            changed_features.sort(key=lambda x: x["importance"], reverse=True)
            
            # Create level explanation
            cf_class = self._predict_class(cf)
            level_explanation = {
                "level": i + 1,
                "changed_features": changed_features,
                "original_class": self._predict_class(current),
                "counterfactual_class": cf_class,
                "original_probabilities": self._predict_prob(current).tolist(),
                "counterfactual_probabilities": self._predict_prob(cf).tolist(),
                "counterfactual": cf.tolist()  # Store the full counterfactual
            }
            
            explanations.append(level_explanation)
            current = cf
            
            # Print the explanation
            print(f"\nLevel {i+1} Counterfactual (Class {cf_class} - {self.class_names[cf_class]}):")
            print("Changed features:")
            for f in changed_features:
                print(f"  - {f['feature']}: {f['original_value']} -> {f['counterfactual_value']}")
            
        return {
            "success": True,
            "original_instance": instance.tolist(),
            "original_class": original_class,
            "target_class": target_class,
            "hierarchical_explanations": explanations
        }

def generate_counterfactual_for_index(idx, clf, binary_val_X, binary_val_y, binary_train_X, binary_train_y, 
                                      all_feature_names, numeric_features, min_levels=3):
    """
    Generate counterfactual explanations for a specific instance by index.
    Only generates explanations if the instance is an attack.
    
    Args:
        idx: Index of the instance in the validation set
        clf: Trained classifier model
        binary_val_X: Validation features
        binary_val_y: Validation labels
        binary_train_X: Training features
        binary_train_y: Training labels
        all_feature_names: List of all feature names
        numeric_features: List of numerical feature names
        min_levels: Minimum number of hierarchy levels to generate
        
    Returns:
        Dictionary containing the explanation, or None if not an attack
    """
    # Get the instance
    instance = binary_val_X.iloc[idx].values
    true_class = binary_val_y.iloc[idx]
    predicted_class = clf.predict([instance])[0]
    
    # Skip if not an attack (both true and predicted should be attack)
    if true_class != 1 or predicted_class != 1:
        print(f"\nInstance #{idx} is not an attack or not predicted as an attack.")
        print(f"True class: {'Attack' if true_class == 1 else 'Normal'}")
        print(f"Predicted class: {'Attack' if predicted_class == 1 else 'Normal'}")
        return None
    
    print(f"\n== Explaining Instance #{idx} ==")
    print(f"True class: Attack")
    print(f"Predicted class: Attack")
    
    # Create the explainer with proper feature types
    categorical_indices = [i for i in range(len(all_feature_names)) if all_feature_names[i] not in numeric_features]
    numerical_indices = [i for i in range(len(all_feature_names)) if all_feature_names[i] in numeric_features]
    
    explainer = HierarchicalCounterfactualExplainer(
        model=clf,
        feature_names=all_feature_names,
        categorical_indices=categorical_indices,
        numerical_indices=numerical_indices,
        class_names=["Normal", "Attack"]
    )
    
    # Fit the explainer with training data
    explainer.fit(binary_train_X, binary_train_y)
    
    # Try to get prediction probabilities if available
    try:
        probs = explainer._predict_prob(instance)
        print(f"Prediction probabilities: Normal: {probs[0]:.4f}, Attack: {probs[1]:.4f}")
    except:
        print("Could not get prediction probabilities")
    
    # Generate counterfactual explanations with multiple attempts
    best_explanation = None
    max_levels = 0
    max_attempts = 3
    
    for attempt in range(max_attempts):
        # Try with increasingly more hierarchies
        num_hierarchies = min_levels + attempt * 2
        explanation = explainer.explain_instance(instance, target_class=0, num_hierarchies=num_hierarchies)
        
        if explanation["success"]:
            levels = len(explanation["hierarchical_explanations"])
            if levels >= min_levels:
                best_explanation = explanation
                break
            elif levels > max_levels:
                max_levels = levels
                best_explanation = explanation
    
    # If we found any valid explanation
    if best_explanation:
        # Print summary of the explanation
        print("\n=== COUNTERFACTUAL EXPLANATION SUMMARY ===")
        print(summarize_explanation(best_explanation, numeric_features))
        
        # Plot the changed features if matplotlib is available
        try:
            # Prepare data for visualization
            changed_features = []
            feature_importances = []
            
            for level in best_explanation["hierarchical_explanations"]:
                for feature in level["changed_features"]:
                    changed_features.append(feature["feature"])
                    feature_importances.append(feature["importance"])
            
            # Create a DataFrame for visualization
            viz_df = pd.DataFrame({
                "Feature": changed_features,
                "Importance": feature_importances
            })
            
            # Aggregate by feature (in case a feature appears in multiple levels)
            agg_df = viz_df.groupby("Feature").sum().reset_index()
            agg_df = agg_df.sort_values("Importance", ascending=False)
            
            # Plot
            plt.figure(figsize=(10, 6))
            sns.barplot(x="Importance", y="Feature", data=agg_df.head(10))
            plt.title(f"Top Features Changed for Instance #{idx}")
            plt.tight_layout()
            plt.show()
            
        except Exception as e:
            print(f"Could not generate visualization: {e}")
        
        return best_explanation
    else:
        print("Could not generate any valid counterfactual explanations.")
        return None

def summarize_explanation(explanation, numeric_features):
    """
    Summarize a counterfactual explanation in a human-readable format
    
    Args:
        explanation: Dictionary containing the explanation
        numeric_features: List of numeric feature names
        
    Returns:
        String with human-readable summary
    """
    if not explanation or not explanation.get("success", False):
        return "No valid explanation found"
        
    original_class = explanation["original_class"]
    target_class = explanation["target_class"]
    class_names = ["Normal", "Attack"]
    
    summary = f"To change from {class_names[original_class]} to {class_names[target_class]}, make these changes:"
    
    for level in explanation["hierarchical_explanations"]:
        level_num = level["level"]
        summary += f"\n\nLevel {level_num} changes (importance order):"
        
        for i, feature in enumerate(level["changed_features"]):
            name = feature["feature"]
            old_val = feature["original_value"]
            new_val = feature["counterfactual_value"]
            
            # Format the feature change based on type
            # Check if the feature is in the numerical features list
            is_numerical = name in numeric_features
            
            if is_numerical:
                change_desc = f"from {old_val:.2f} to {new_val:.2f}"
            else:
                change_desc = f"from {old_val} to {new_val}"
                
            summary += f"\n  {i+1}. Change {name} {change_desc}"
    
    return summary

# Function to demonstrate counterfactual explanations
def run_counterfactual_demo():
    print("\n=== Counterfactual Explanation Demo ===")
    
    # Define all feature names for the classifier
    all_feature_names = to_fit.columns.tolist()
    
    # Try to find an attack instance
    attack_indices = []
    for i in range(len(binary_val_X)):
        if binary_val_y.iloc[i] == 1 and clf.predict([binary_val_X.iloc[i].values])[0] == 1:
            attack_indices.append(i)
    
    if not attack_indices:
        print("No attack instances found in validation data.")
        return
    
    # Choose a random attack instance
    idx = random.choice(attack_indices)
    
    # Generate the explanation
    explanation = generate_counterfactual_for_index(
        idx=idx,
        clf=clf, 
        binary_val_X=binary_val_X,
        binary_val_y=binary_val_y,
        binary_train_X=binary_train_X,
        binary_train_y=binary_train_y,
        all_feature_names=all_feature_names,
        numeric_features=numeric_features,
        min_levels=3
    )
    
    # Save the explanation to file if generated
    if explanation:
        try:
            import json
            output_file = f"counterfactual_explanation_{idx}.json"
            
            with open(output_file, 'w') as f:
                json.dump(explanation, f, indent=2)
            
            print(f"\nExplanation saved to {output_file}")
        except Exception as e:
            print(f"Could not save explanation to file: {e}")
            
    return explanation

# Allow user to generate counterfactual for a specific index
def get_counterfactual_for_user_instance():
    try:
        # Define all feature names for the classifier
        all_feature_names = to_fit.columns.tolist()
        
        instance_idx = int(input("Enter the index of the instance to explain: "))
        
        # Generate the explanation
        explanation = generate_counterfactual_for_index(
            idx=instance_idx,
            clf=clf, 
            binary_val_X=binary_val_X,
            binary_val_y=binary_val_y,
            binary_train_X=binary_train_X,
            binary_train_y=binary_train_y,
            all_feature_names=all_feature_names,
            numeric_features=numeric_features,
            min_levels=3
        )
        
        # Save the explanation to file if generated
        if explanation:
            import json
            output_file = f"counterfactual_explanation_{instance_idx}.json"
            
            with open(output_file, 'w') as f:
                json.dump(explanation, f, indent=2)
            
            print(f"\nExplanation saved to {output_file}")
    
    except ValueError:
        print("Please enter a valid integer index.")
    except Exception as e:
        print(f"An error occurred: {e}")

# Compare different XAI methods
def compare_xai_methods(instance_idx):
    """
    Compare LIME, SHAP, and Counterfactual explanations for a single instance
    
    Args:
        instance_idx: Index of the instance to explain
    """
    try:
        print(f"\n=== Comparing XAI Methods for Instance #{instance_idx} ===")
        
        # Define all feature names for the classifier
        all_feature_names = to_fit.columns.tolist()
        
        # 1. Get the instance
        instance = binary_val_X.iloc[instance_idx].values
        true_class = binary_val_y.iloc[instance_idx]
        predicted_class = clf.predict([instance])[0]
        
        if true_class != 1 or predicted_class != 1:
            print(f"Instance #{instance_idx} is not an attack or not predicted as an attack.")
            return
        
        print(f"Instance #{instance_idx}")
        print(f"True class: {'Attack' if true_class == 1 else 'Normal'}")
        print(f"Predicted class: {'Attack' if predicted_class == 1 else 'Normal'}")
        
        # 2. LIME explanation
        print("\n--- LIME Explanation ---")
        try:
            lime_exp = explainer.explain_instance(data_row=x_test.iloc[instance_idx], 
                                                predict_fn=model.predict_proba)
            print("LIME Feature Importance:")
            lime_list = lime_exp.as_list()
            for feature, value in lime_list[:5]:  # Show top 5 features
                print(f"  - {feature}: {value:.4f}")
        except Exception as e:
            print(f"Error generating LIME explanation: {e}")
        
        # 3. SHAP explanation
        print("\n--- SHAP Explanation ---")
        try:
            # Get SHAP values
            shap_instance_values = shap_values[instance_idx]
            
            # Get top features by absolute SHAP value
            shap_values_array = shap_instance_values.values
            top_shap_indices = np.argsort(np.abs(shap_values_array))[-5:]  # Top 5 features
            
            print("SHAP Feature Importance:")
            for idx in reversed(top_shap_indices):
                feature_name = x_test.columns[idx]
                shap_value = shap_values_array[idx]
                print(f"  - {feature_name}: {shap_value:.4f}")
        except Exception as e:
            print(f"Error generating SHAP explanation: {e}")
        
        # 4. Counterfactual explanation
        print("\n--- Counterfactual Explanation ---")
        explanation = generate_counterfactual_for_index(
            idx=instance_idx,
            clf=clf, 
            binary_val_X=binary_val_X,
            binary_val_y=binary_val_y,
            binary_train_X=binary_train_X,
            binary_train_y=binary_train_y,
            all_feature_names=all_feature_names,
            numeric_features=numeric_features,
            min_levels=3
        )
        
        # 5. Summary comparison
        print("\n=== Comparison Summary ===")
        print("- LIME provides feature importance for the current prediction")
        print("- SHAP shows how each feature contributes to pushing the prediction from the base value")
        print("- Counterfactual explanations show what changes are needed to change the prediction")
        
    except Exception as e:
        print(f"Error comparing XAI methods: {e}")

print("\nCounterfactual Explanation functionality has been added.")
print("You can use the following functions:")
print("1. run_counterfactual_demo() - Run a demo with a random attack instance")
print("2. get_counterfactual_for_user_instance() - Explain a specific instance")
print("3. compare_xai_methods(instance_idx) - Compare LIME, SHAP, and Counterfactual explanations")